[package]
name = "ashpd-demo"
version = "0.1.0"
authors = ["Bilal Elmoussaoui <bil.elmoussaoui@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4"
pretty_env_logger = "0.4"
gettext-rs = { version = "0.6", features = ["gettext-system"] }
gtk-macros = "0.2"
once_cell = "1.5"
futures = "0.3"
gst_video = {package="gstreamer-video", git="https://gitlab.freedesktop.org/gstreamer/gstreamer-rs"}
gst_base = {package="gstreamer-base", git="https://gitlab.freedesktop.org/gstreamer/gstreamer-rs"}
gst = {package="gstreamer", git="https://gitlab.freedesktop.org/gstreamer/gstreamer-rs"}


[dependencies.gtk]
package = "gtk4"
git = "https://github.com/gtk-rs/gtk4-rs"

[dependencies.ashpd]
git = "https://github.com/bilelmoussaoui/ashpd"
features = ["feature_gtk4"]

[dependencies.adw]
package = "libadwaita"
git = "https://gitlab.gnome.org/bilelmoussaoui/libadwaita-rs"
