name: Update DBus interfaces

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * 0"  # every Sunday at 03:00 UTC

jobs:
  update-dbus-xml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y git libxml2-utils

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config --global --add safe.directory "${GITHUB_WORKSPACE}"

      - name: Run Python script to update interfaces
        run: python3 update-interfaces.py

      - name: Commit and create PR
        uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update portal DBus XMLs"
          branch: update-dbus-xmls
          title: "Update portal DBus XMLs"
          body: "Automated update of exported portal interfaces."
          author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
          delete-branch: true
